### ISSUE TITLE
In the case of parallel execution, one succeeds, but all others fail.

### ISSUE THREAD

**Issue by k-in** [Azure/aca-review-apps#58]
While provisioning a container app is in progress, other provision reques will be fail.
We need guidance or solution to this issue.

**Comment by koudaiii** [comment]
Cloud you please comment on how to do it, as well as any logs or screen shots?

**Comment by k-in** [comment]
If the Container App is in the process of provisioning, the following error will occur when the GitHub action is executed.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/72186259/191441190-a29b6065-504b-49d1-ab78-d8348726a2cd.png">

**Comment by horihiro** [comment]
Looks like retry logic is needed, further investigation is needed to decide which layer the logic should be implemeted in.

**Comment by koudaiii** [comment]
I think the workaround would be to implement retry. In addition, I think that it is necessary to decide what it should be by discussing it separately.

**Comment by horihiro** [comment]
`@azure/core-rest-pipeline` already has `retry` logic as described at the following documentation.
https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-rest-pipeline/documentation/pipeline.md

But the status code `409` in this case is not included in retry-target-response-codes as far as reading the following code.
https://github.com/Azure/azure-sdk-for-js/blob/82996230773ab8295f06b17a8b6f449f9d9f2a8c/sdk/core/core-rest-pipeline/src/retryStrategies/exponentialRetryStrategy.ts#L81-L94

**Comment by horihiro** [comment]
Ref: https://github.com/Azure/azure-sdk-for-js/issues/23298

**Comment by k-in** [comment]
As guidance, at a minimum, the following guidance should be guided.

- Run only one workflow at a time  
Ref: [Workflow syntax for GitHub Actions](https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)

**Comment by horihiro** [comment]
The guidance is about GitHub Actions workflows' concurrency.

On the other hands, this issue can be happened when the action runs during any updates from Azure portal, CLI, PowerShell or REST API.

**Comment by horihiro** [comment]
@k-in 
Could you please try an action `horihiro/aca-preview@v0.2.0-alpha2` that retries 10 times at maxiumum and let me know the result?

**Comment by horihiro** [comment]
Released `horihiro/aca-preview@v0.2.0-alpha3` that exposes max retry count as an input `max-retries`.

https://github.com/horihiro/aca-preview/blob/5d75583459e1a53ed6ebf3f8d956e0144bb7eb68/src/main.ts#L127-L137

**Comment by horihiro** [comment]
By design, currently,
